-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Apr 02, 2017 at 12:42 AM
-- Server version: 10.1.19-MariaDB
-- PHP Version: 5.6.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `hack`
--

-- --------------------------------------------------------

--
-- Table structure for table `coursesdetails`
--

CREATE TABLE `coursesdetails` (
  `CourseName` varchar(150) NOT NULL,
  `Name` text NOT NULL,
  `Eligibility` varchar(200) NOT NULL,
  `Experience` varchar(250) NOT NULL,
  `TerminalCompetency` varchar(1000) NOT NULL,
  `Duration` varchar(250) NOT NULL,
  `ContentOfferings` varchar(1000) NOT NULL,
  `ContentAvailabilityinRegionalLanguages` varchar(250) NOT NULL,
  `SpecialFeature` varchar(1000) NOT NULL,
  `dropdown` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `coursesdetails`
--

INSERT INTO `coursesdetails` (`CourseName`, `Name`, `Eligibility`, `Experience`, `TerminalCompetency`, `Duration`, `ContentOfferings`, `ContentAvailabilityinRegionalLanguages`, `SpecialFeature`, `dropdown`) VALUES
('Hospital Assistant', 'General Duty Assistant', 'Minimum Qualification - 10th pass', 'No Experience', 'His course encompasses 21 out of 21 National Occupational Standards (NOS) of "General Duty Assistant". Qualification Stack - HSS/Q5101 issued by Health Care Sector Skill Council.It is aimed at training candidates for the job of ''General Duty Assistant'' in the Health Sector.\r\nAfter successful completion of the course, the individual will be able to transport a patient into the hospital from one ward to the other as needed, AID and support the patient in managing personal hygiene, support the nurses while administrating the drugs and drawing samples, handle and manage hospital equipment including medical and surgical equipment, help the patient in feeding and eliminating waste and ensure the comfort of the patient at all times.', '430 Hours [include domain skills, soft skills, English and digital literacy]', '# Multimedia Videos # Session Plan # Syllabus # Participant Handbook # Trainer''s Guide # Assessment Guide # Posters', 'Available in 6 regional languages', 'The course focuses on imparting knowledge and practical skills that enable the learner to deliver ''Patient Care with empathy''. It begins with a tour of a hospital, an understanding of the job role, followed by an inside into the human anatomy and physiology, common infectious diseases, universal precautions to be taken and sterilization procedures. These offer good scaffolding for the skill competencies that follow. The various task in patient care are demonstrated through show and tell methodology step y step. The judicious use of 3D animations for the understanding of concepts and the use of instructional videos to demonstrate the various task expected of a GENERAL DUTY ASSISTANT, make learning effective and enriching.', 'Hospitality'),
('Dairy Farmer', 'Dairy Farmer/Entrepreneur', 'Minimum Qualification - 5th Pass', '1 year prior experience in Animal Care & Management, preferable.', 'The course encompasses 8 out of 8 National Occupational Standards (NOS) of "Dairy Farmer/Entrepreneur" Qualification pack AGR/Q4101 issued by "Agriculture Sector Skill Council of India". This Course is aimed at training candidates for the job of "Dairy Farmer/Entrepreneur" in the Agriculture Sector.\r\nAfter completing this programme, the individual will be able to prepare and maintain livestock accommodation, establish livestock within the accommodation, provide feed and water for livestock, maintain healthy performance of livestock, perform milk through and machine, forage conservation.', '228 hrs [Includes Domain skills, Soft skills, English, Digital literacy', '# Session Plan # Syllabus # Participant # Handbook # Trainer''s Guide # Assessment Guide', 'Available in English and in 4 regional languages', 'Since most of the curriculum is practical oriented, the course content is made pictorial with real photographs, easy to understand with minimal reading material. The content is mapped to all occupational standards.', 'Agriculture'),
('Computer Hardware Technician', 'Computer Hardware Technician', 'Minimum Qualification - Class 8th Pass', 'No Experience', 'This course is aimed at training candidates for the job of “Computer Hardware Technician”. The content for this course has the twin objectives of imparting knowledge of hardware (the PC, its components, installations) as well as the skill to troubleshoot. The terminal goal of the course is to equip learners with skills needed to be a Hardware Maintenance Technician.', '240 hrs [Includes Domain skills, Soft skills, English, Digital literacy.', '# Multimedia Content # Trainer''s Guide # Participant Handbook # Assessment Guide # Session Plan # Domain specific Posters', 'Available in 6 regional languages\r\n ', 'Every Computer Hardware Technician is expected to be able to assemble a computer, install hardware and software and troubleshoot. While 3D animations have been used judiciously to explain concepts, the highpoint of the course are the video demonstrations of the procedural content, the best practices and the do''s and don''ts.\r\nThe multimedia content has been developed to demonstrate, through videos, the procedure step by step. Besides videos, other media mixes such as text, voice, graphics compliment the instructional videos. Videos are reinforced with short text based-instructions and voice. The demonstrations follow the tried and tested skill-building methodology, namely SHOW-TELL-TRY–TEST.', 'Electronics'),
('Banking Financial Services & Insurance', 'Mutual Fund Agent (MFA)', 'Minimum Qualification - 12th pass', 'No Experience', 'The course encompasses 4 out of 4 National Occupational Standards (NOS) of “Mutual Fund Agent” Qualification Pack BSC / Q 0601 issued by Banking, Financial Services and Insurance (BFSI) sector. The course is aimed at training candidates for the job of “Mutual Fund Agent”, in the BFSI industry. After completing the course, the individual will be able to conduct research, market and sell mutual fund, assist with purchase of mutual fund, perform after-sales activities.', '220 hrs [Includes Domain skills, Soft skills, English, Digital literacy]', '# Session Plan # Syllabus # Participant Handbook # Trainer''s Guide # Assessment Guide', 'Available in English language only', 'The content has been given a unique treatment to make understanding easier and engaging. Rohit Sharma is a newcomer to the industry and aspires to be a Mutual Fund Agent. His friend, Puneet, and an expert in the field, helps Rohit understand the subject. The question-answer technique, adopted mirrors the questions in the minds of the learners, offers content in smaller doses and is more effective. The generous use of graphic organizers to represent concepts helps in better retention.', 'Banking'),
('Software Engineering ( Non Engineers)', 'IT for Non-Engineers', 'Minimum Qualification - Graduation from any stream other than engineering.', 'No Experience', 'This course is aimed at training candidates for the job of Software Developer in the IT-ITeS sector. After successful completion of the course, the individual will be able to build web applications using Visual Studio.Net and web applications using J2EE.\r\n ', '400 hrs [Includes Domain skills, Soft skills, English, Digital literacy]', '# Multimedia Videos # Session Plan # Syllabus # Participant Handbook # Trainer''s Guide # Assessment Guide # Practical Guide', 'Available in English', 'The course has two components to it, a generic one followed by an elective that the learner can pick. The generic component builds, in the learner, the basic programming constructs, the ''C'' language. It is followed by object oriented programming, HTML coding and queries in RDBMS. Subsequent to this are electives - building web applications using Visual Studio.Net and building web applications using J2EE. Interactive multimedia content hand holds the learner in building programming logic.\r\nIn addition, are a series of video based modules on soft skills. Abhishek, a newbie in a software development firm learns it the hard way, that no matter how good his programming skills are, without soft skills he will not be able to climb up the corporate ladder.', 'IT & ITES'),
('Arc Welding', 'Welding Assistant', 'Minimum Qualification - 8th pass', 'No Experience', 'This course encompasses 4 out of 4 National Occupational Standards (NOS) of Welding Assistant Qualification Pack ASC/Q3101 issued by Automotive Skills Development Council. It is aimed at training candidates for the job of Welding Assistant, in the Automotive industry.', '240 hrs [Includes Domain skills, Soft skills, English, Digital literacy]', '# Multimedia Videos # Session Plan # Syllabus # Participant Handbook # Trainer''s Guide # Assessment Guide # Posters', 'Available in 6 regional languages', 'The arc formation process, how to strike an arc, the different types of welds and the procedure to create a weld in fillet joint and a groove joint in various weld positions - all these form the core of the course. The various tools to be used, safety measures to be taken, other knowledge competencies including the different types of joints, defects, methods of inspecting the same, complete the course curriculum.\r\nA series of episodes on soft skills feature a group of welders who live under the same roof, sharing accommodation. Be it lessons on anger management, health, grooming, communication or stress management, the welders help each other learn the importance of these in work life and personal life.\r\n3D animations coupled with video demonstrations of procedural content are the high points of this course.', 'Automotive'),
('Shuttering Carpentry', 'Helper Carpenter - Shuttering & Scaffolding', 'Minimum Qualification - 8th pass', 'No Experience', 'This course encompasses 6 out of 6 National Occupational Standards (NOS) of “Helper Carpenter - Shuttering and Scaffolding” Qualification Pack CON/Q 0301 issued by Construction Skill Development Council. It is aimed at training candidates for the job of “Helper Carpenter - Shuttering and Scaffolding”, in the construction industry.\r\nAfter successful completion of the course, the individual must be able to provide support in making, assembling, erecting and dismantling all types of conventional formwork and scaffolding arrangements & systems. He is expected to know basics of carpentry and also about the system form work and shuttering.', '240 hrs [Includes Domain skills, Soft skills, English, Digital literacy]', '# Multimedia Videos # Session Plan # Syllabus # Participant Handbook # Trainer''s Guide # Assessment Guide ', 'Available in 6 regional languages', 'The course clearly touches upon three distinct domains of learning, namely Knowledge, Skills and Attitude. The knowledge competencies bring insights into the different types of shuttering materials, tools and equipment, measurements and calculations, safety, engineering drawings among others. The performance competencies cover tools, techniques and method of form work in great detail. Functional English and Life skills add value to the course.\r\nHD videos capture on camera the step by step procedure of performing the various tasks expected of a Helper Carpenter, thereby enabling the learning by doing approach.', 'Construction'),
('MIG Welding', 'Welding Technician Level 3', 'Minimum Qualification - 10th pass', 'No Experience', 'This course encompasses 8 out of 8 National Occupational Standards (NOS) of Welding Technician Level 3 Qualification Pack ASC/Q3102 issued by Automotive Skills Development Council. It is aimed at training candidates for the job of “Welding Technician Level 3” in the Automotive Sector', '400 hrs [Includes Domain skills, Soft skills, English, Digital literacy]', '# Multimedia Videos # Session Plan # Syllabus # Participant Handbook # Trainer''s Guide # Assessment Guide # Posters', 'Available in 6 regional languages.', 'The terminal goal of the course is to enable the learner to perform GMAW welding. It begins with a series of knowledge based competencies on safety, electricity, metallurgy. Followed by these, are the actual tasks which are grouped under three segments - before welding, during welding and after welding. A specialised segment on functional English is included that aims to help the learner to be able to read and interpret engineering drawings, manuals, safety instructions and other essential instructions/content that may be in the English language.\r\nA series of episodes on soft skills feature a group of welders who live under the same roof, sharing accommodation. Be it lessons on anger management, health, grooming, communication or stress management, the welders help each other learn the importance of these in work life and personal life.\r\nThe deliberate use of 3D animations ensure that the learner is able to view the weld clearly.', 'Capital Goods'),
('Food & Beverages Production (Assistant Cook)', 'Assistant Cook', 'Minimum Qualification - 10th pass', 'No Experience', 'This course is aimed at training candidates for the job of “Assistant Cook”, in the “Hospitality” industry. After successful completion of the course, the individual will be able to prepare sauces, soups, sandwiches, egg based preparations, pasta, set up live counters and prepare a four course menu for two.', '480 hrs [Includes Domain skills, Soft skills, English, Digital literacy]', '#  Multimedia Videos with a Pictionary # Session Plan # Syllabus # Participant Handbook # Trainer''s Guide # Assessment Guide # Recipe Booklet # Posters', 'Available in 6 regional languages.', 'A series of visually rich video demonstrations capture knowledge and skill competencies. Trained professional actors demonstrate, through a series of examples and non-examples, various scenarios in a 5-star kitchen exposing learners to the technical as well as behavioural (soft skills) competencies also that need to be honed, thereby completing the learning experience.\r\nA Multimedia Pictionary captures terms and terminologies that are difficult to pronounce and spell, showing rich visuals of these, with explanations, and additionally audio clips for their correct pronunciation.\r\nAn additional booklet, the Recipe booklet, contains 14 menus, a combination of Indian as well as Western. Each menu is meant to serve 2 to 4 guests. For each course of every menu, learners are given the ingredient list and the procedure to prepare. These are to be tried out as part of the practical sessions that will be evaluated.', 'Tourism and Hospitality');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
